#!/bin/bash

: ${DOCKERDNS_FILE:="/etc/docker0-dnsmasq.d/docker0-network"}
: ${DOCKERDNS_SUFFIX:=".docker.local"}

echo -n '' > $DOCKERDNS_FILE || exit

for CONTAINER in `docker ps -q`
do
	NAME=`docker inspect -f "{{.Name}}" $CONTAINER | sed -e 's/^\/*//'`
	ADDRESS=`docker inspect -f "{{.NetworkSettings.IPAddress}}" $CONTAINER`
	echo "add DNS record: $NAME$DOCKERDNS_SUFFIX => $ADDRESS"
	echo "host-record=$NAME,$NAME$DOCKERDNS_SUFFIX,$ADDRESS" >> $DOCKERDNS_FILE
done

echo "$DOCKERDNS_FILE updated."

systemctl restart docker0-dnsmasq.service
systemctl status docker0-dnsmasq.service -l
